name: Sync data and apps to xp version

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2

      - name: Git setup
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Apply changes
        run: |
          git checkout xp
          git checkout main -- src/apps src/data.ts
          git add src/apps src/data.ts
          git commit -m "Sync src/apps and src/data.ts with main"
          git push origin xp
