name: Sync data and apps to xp version

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: xp
          ref: xp

      - name: Apply changes
        run: |
          cp -r src/apps xp/src/
          cp src/data.ts xp/src/
          cp -n -R public/apps xp/public/
          cp -R public/projets xp/public/
          cd xp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync data and apps from main branch"
          git push origin xp
